# Generated by Django 5.0.3 on 2024-03-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_approved_by_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comments',
            new_name='text',
        ),
    ]
